# Generated by Django 4.2.7 on 2025-05-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="live_link",
            field=models.URLField(blank=True),
        ),
    ]
