# Generated by Django 4.2.7 on 2025-05-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_skill_options_remove_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
